#!/bin/bash
echo "Running pre-commit hook"
/usr/bin/curl --user devops:devops -s http://localhost:8080/job/M2/build?token=12345

echo "Trying to fetch build status for current build......"
sleep 10
JSON=$(wget -qO- http://127.0.0.1:8080/job/M2/lastBuild/api/json)
RESULT=$(echo $JSON | grep -oe '"result":"\w\+"' | cut -d \" -f4 | tr -d '\n')

while [ -z $RESULT ]; do
    echo "Waiting for the build to get completed"
    sleep 5
    JSON=$(wget -qO- http://127.0.0.1:8080/job/M2/lastBuild/api/json)
    RESULT=$(echo $JSON | grep -oe '"result":"\w\+"' | cut -d \" -f4 | tr -d '\n')
done

echo "Found build status"

if [ $RESULT = "FAILURE" ]; then
    exit 1
fi

