#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
echo "Running pre commit hook"
for FILE in `git diff-index --name-status HEAD -- | cut -c3-` ; do
    if [ -f $FILE ]; then
        result=$(python detect_keys.py $FILE)
        if [ $result = "true" ]; then
            echo "$FILE contains a key!!"
            echo "Rejecting this commit"
            exit 1
        fi
    fi
done
